# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b44f41dcd593168584e866060800de3f182d93681e3208fa202c01e6d427f1e15d65a8894ce214cdb358eceaf3e481d380d2f2d942a6f681ac2387e9393ea1b

test:
  secret_key_base: c8309b7720fc07461b7eb266b6a6b1d5457cc3a6898ee448aa3f794dfae314d3adcbd5c92724b22ca05e477597c18bb30408071ddb0eaf68d026f82e77163370

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
